--- # My first Yaml playbook fo Ansible
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/webdefaults.Yml
  vars_prompt:
    - name: web_domain
      prompt: web Domain
  tasks:
    - name: Install apache Web server
      action: apt name=apache2 state=installed
      notify: Restart HTTPD
    - name: Install the Lynx Web Browser
      action: apt name={{pkg_lynx}} state=installed
  handlers:
    - name: Restart HTTPD
      action: service name=apache2 state=restarted
